// ============================================================================
// AI MODES (P11) — Architect / Builder / Report
// ----------------------------------------------------------------------------
// Three specialized Gemini endpoints:
//   • architect  — suggests initial CRM config from a business description
//   • builder    — generates one artifact (workflow, email, landing) from
//                  a one-line intent
//   • report     — picks a whitelisted aggregate query to answer a
//                  natural-language question, runs it, returns chart + text
//
// All calls go through gemini-2.0-flash via the existing GEMINI_API_KEY.
// SQL is NEVER generated by the model — the report mode only chooses
// which of a handful of pre-baked queries to execute, then narrates
// the result.
// ============================================================================

import { GoogleGenerativeAI } from "@google/generative-ai";
import { prisma } from "../config/database";
import { env } from "../config/env";
import { badRequest } from "../middleware/errorHandler";

const genAI = env.GEMINI_API_KEY
  ? new GoogleGenerativeAI(env.GEMINI_API_KEY)
  : null;

async function gemini(prompt: string): Promise<string> {
  if (!genAI) throw badRequest("AI is not configured on this tenant");
  const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });
  const result = await model.generateContent(prompt);
  return result.response.text().trim();
}

function stripFences(s: string): string {
  return s.replace(/^```(?:json)?\s*/i, "").replace(/\s*```\s*$/i, "");
}

function safeJson<T>(s: string): T | null {
  try {
    return JSON.parse(stripFences(s)) as T;
  } catch {
    return null;
  }
}

// ──────────────────────────────────────────────────────────────────────
// ARCHITECT
// ──────────────────────────────────────────────────────────────────────

export interface ArchitectInput {
  businessDescription: string;
  locale?: "en" | "ar" | "tr";
}

export interface ArchitectOutput {
  pipelineStages: Array<{ name: string; probability?: number }>;
  customFields: Array<{
    entity: "customer" | "deal";
    name: string;
    type: "text" | "number" | "date" | "select";
    options?: string[];
  }>;
  emailTemplates: Array<{ name: string; subject: string; bodyText: string }>;
  rationale: string;
}

export async function architect(
  input: ArchitectInput
): Promise<ArchitectOutput> {
  const desc = input.businessDescription.trim();
  if (!desc) throw badRequest("businessDescription is required");
  const prompt = `You are configuring a new Zyrix CRM for a business.
Business: ${desc}

Return strict JSON with:
  pipelineStages: array of { name, probability (0-100) } between 4 and 7 stages
  customFields: array of { entity ("customer"|"deal"), name, type ("text"|"number"|"date"|"select"), options? (for select) }, max 6 items total
  emailTemplates: 2-3 templates with { name, subject, bodyText }, suited to the business
  rationale: 2-sentence explanation of the choices

Reply with ONLY the JSON, no code fences, no commentary.`;
  const raw = await gemini(prompt);
  const parsed = safeJson<ArchitectOutput>(raw);
  if (!parsed) {
    throw badRequest("AI returned non-JSON; try again with a longer business description");
  }
  return parsed;
}

// ──────────────────────────────────────────────────────────────────────
// BUILDER
// ──────────────────────────────────────────────────────────────────────

export interface BuilderInput {
  intent: string;
  artifactType: "workflow" | "email" | "landing";
}

export interface BuilderOutputWorkflow {
  artifactType: "workflow";
  name: string;
  description: string;
  trigger: { type: string; config: Record<string, unknown> };
  actions: Array<{
    type: string;
    config: Record<string, unknown>;
  }>;
}

export interface BuilderOutputEmail {
  artifactType: "email";
  name: string;
  subject: string;
  bodyHtml: string;
  bodyText: string;
}

export interface BuilderOutputLanding {
  artifactType: "landing";
  title: string;
  subtitle: string;
  bullets: string[];
  callToAction: { label: string; href: string };
  html: string;
}

export type BuilderOutput =
  | BuilderOutputWorkflow
  | BuilderOutputEmail
  | BuilderOutputLanding;

export async function builder(input: BuilderInput): Promise<BuilderOutput> {
  const intent = input.intent.trim();
  if (!intent) throw badRequest("intent is required");
  const schema =
    input.artifactType === "workflow"
      ? `{"artifactType": "workflow", "name": "...", "description": "...",
          "trigger": {"type": "customer.created|deal.stage_changed|schedule.daily", "config": {}},
          "actions": [{"type": "send_email|ai_generate_email|create_task|...", "config": {}}]}`
      : input.artifactType === "email"
        ? `{"artifactType": "email", "name": "...", "subject": "...", "bodyHtml": "<html>...</html>", "bodyText": "..."}`
        : `{"artifactType": "landing", "title": "...", "subtitle": "...",
            "bullets": ["...", "...", "..."],
            "callToAction": {"label": "...", "href": "https://..."},
            "html": "<html>...</html>"}`;
  const prompt = `Build a ${input.artifactType} for this intent: "${intent}"
Use only these workflow trigger types: customer.created, deal.stage_changed, schedule.daily, webhook.received.
Use only these action types: send_email, send_whatsapp_message, create_task, update_deal_stage, update_customer_status, add_tag, call_webhook, ai_generate_email, ai_summarize, ai_categorize, ai_translate, send_notification, update_field, webhook_call.

Return strict JSON matching this shape:
${schema}

Reply with ONLY the JSON, no code fences, no commentary.`;
  const raw = await gemini(prompt);
  const parsed = safeJson<BuilderOutput>(raw);
  if (!parsed) throw badRequest("AI returned non-JSON — try rephrasing the intent");
  return parsed;
}

// ──────────────────────────────────────────────────────────────────────
// REPORT
// ──────────────────────────────────────────────────────────────────────
// Whitelisted aggregate query catalog. Each entry knows how to compute
// its own result scoped to companyId; Gemini picks which one fits the
// user's question, then we run it locally. No free-form SQL is ever
// sent to the model.
// ──────────────────────────────────────────────────────────────────────

type QueryId =
  | "top_customers_by_revenue_30d"
  | "top_customers_by_revenue_90d"
  | "deals_by_stage"
  | "won_deals_last_30d"
  | "won_deals_last_90d"
  | "new_customers_last_30d"
  | "activities_by_user_last_30d"
  | "top_users_by_won_revenue_90d";

const QUERY_CATALOG: Array<{ id: QueryId; description: string }> = [
  { id: "top_customers_by_revenue_30d", description: "Top customers ranked by won deal revenue in the last 30 days" },
  { id: "top_customers_by_revenue_90d", description: "Top customers ranked by won deal revenue in the last 90 days" },
  { id: "deals_by_stage", description: "Deal counts + value grouped by pipeline stage, all open deals" },
  { id: "won_deals_last_30d", description: "Number and total value of deals won in the last 30 days" },
  { id: "won_deals_last_90d", description: "Number and total value of deals won in the last 90 days" },
  { id: "new_customers_last_30d", description: "Count of new customers created in the last 30 days" },
  { id: "activities_by_user_last_30d", description: "Activity count per user in the last 30 days" },
  { id: "top_users_by_won_revenue_90d", description: "Sales reps ranked by their won deal revenue in the last 90 days" },
];

async function runQuery(id: QueryId, companyId: string): Promise<unknown> {
  const now = new Date();
  const days = (n: number) =>
    new Date(now.getTime() - n * 24 * 60 * 60 * 1000);
  switch (id) {
    case "top_customers_by_revenue_30d":
    case "top_customers_by_revenue_90d": {
      const sinceDays = id.endsWith("30d") ? 30 : 90;
      const grouped = await prisma.deal.groupBy({
        by: ["customerId"],
        where: { companyId, stage: "won", actualCloseDate: { gte: days(sinceDays) } },
        _sum: { value: true },
        _count: { _all: true },
        orderBy: { _sum: { value: "desc" } },
        take: 10,
      });
      const ids = grouped.map((g) => g.customerId);
      const customers = await prisma.customer.findMany({
        where: { id: { in: ids }, companyId },
        select: { id: true, fullName: true, companyName: true },
      });
      const lookup = new Map(customers.map((c) => [c.id, c]));
      return grouped.map((g) => ({
        customerId: g.customerId,
        customer: lookup.get(g.customerId),
        wonRevenue: g._sum.value ?? 0,
        dealsWon: g._count._all,
      }));
    }
    case "deals_by_stage": {
      const grouped = await prisma.deal.groupBy({
        by: ["stage"],
        where: { companyId },
        _sum: { value: true },
        _count: { _all: true },
      });
      return grouped.map((g) => ({
        stage: g.stage,
        count: g._count._all,
        value: g._sum.value ?? 0,
      }));
    }
    case "won_deals_last_30d":
    case "won_deals_last_90d": {
      const since = days(id.endsWith("30d") ? 30 : 90);
      const agg = await prisma.deal.aggregate({
        where: { companyId, stage: "won", actualCloseDate: { gte: since } },
        _sum: { value: true },
        _count: { _all: true },
      });
      return {
        count: agg._count._all,
        total: agg._sum.value ?? 0,
      };
    }
    case "new_customers_last_30d": {
      const count = await prisma.customer.count({
        where: { companyId, createdAt: { gte: days(30) } },
      });
      return { count };
    }
    case "activities_by_user_last_30d": {
      const grouped = await prisma.activity.groupBy({
        by: ["userId"],
        where: { companyId, createdAt: { gte: days(30) } },
        _count: { _all: true },
      });
      const ids = grouped.map((g) => g.userId);
      const users = await prisma.user.findMany({
        where: { id: { in: ids }, companyId },
        select: { id: true, fullName: true },
      });
      const lookup = new Map(users.map((u) => [u.id, u]));
      return grouped.map((g) => ({
        userId: g.userId,
        user: lookup.get(g.userId),
        count: g._count._all,
      }));
    }
    case "top_users_by_won_revenue_90d": {
      const grouped = await prisma.deal.groupBy({
        by: ["ownerId"],
        where: {
          companyId,
          stage: "won",
          actualCloseDate: { gte: days(90) },
        },
        _sum: { value: true },
        _count: { _all: true },
        orderBy: { _sum: { value: "desc" } },
        take: 10,
      });
      const ids = grouped.map((g) => g.ownerId).filter(Boolean) as string[];
      const users = await prisma.user.findMany({
        where: { id: { in: ids }, companyId },
        select: { id: true, fullName: true },
      });
      const lookup = new Map(users.map((u) => [u.id, u]));
      return grouped.map((g) => ({
        ownerId: g.ownerId,
        user: g.ownerId ? lookup.get(g.ownerId) : null,
        wonRevenue: g._sum.value ?? 0,
        dealsWon: g._count._all,
      }));
    }
  }
}

export interface ReportInput {
  companyId: string;
  question: string;
  locale?: "en" | "ar" | "tr";
}

export interface ReportOutput {
  question: string;
  selectedQueryId: QueryId;
  data: unknown;
  narrative: string;
  chart: {
    type: "bar" | "line" | "pie" | "table";
    xKey?: string;
    yKey?: string;
    categoryKey?: string;
    valueKey?: string;
  };
}

export async function report(input: ReportInput): Promise<ReportOutput> {
  const question = input.question.trim();
  if (!question) throw badRequest("question is required");
  const locale = input.locale ?? "en";

  const catalogText = QUERY_CATALOG.map(
    (q) => `- ${q.id}: ${q.description}`
  ).join("\n");

  const pickPrompt = `A user asked: "${question}"
Pick the single best matching query id from this list:
${catalogText}

Reply with ONLY the query id (e.g. "deals_by_stage") — no prose, no quotes.`;
  const pickRaw = (await gemini(pickPrompt)).trim().replace(/['"`]/g, "");
  const selectedQueryId = QUERY_CATALOG.find((q) => q.id === pickRaw)?.id;
  if (!selectedQueryId) {
    throw badRequest(
      `AI picked an unknown query id "${pickRaw}". Rephrase the question.`
    );
  }

  const data = await runQuery(selectedQueryId, input.companyId);

  const narrativePrompt = `Here is the answer to "${question}" as JSON:
${JSON.stringify(data).slice(0, 4000)}

Write a 1-2 sentence narrative (in ${locale}) summarizing the key insight. No preamble — just the summary.`;
  const narrative = await gemini(narrativePrompt);

  // Static chart mapping — keeps the contract stable and avoids the LLM
  // returning incompatible chart specs.
  const chart = chartFor(selectedQueryId);

  return {
    question,
    selectedQueryId,
    data,
    narrative,
    chart,
  };
}

function chartFor(id: QueryId): ReportOutput["chart"] {
  switch (id) {
    case "deals_by_stage":
      return { type: "bar", xKey: "stage", yKey: "count" };
    case "top_customers_by_revenue_30d":
    case "top_customers_by_revenue_90d":
      return { type: "bar", xKey: "customer.fullName", yKey: "wonRevenue" };
    case "activities_by_user_last_30d":
      return { type: "bar", xKey: "user.fullName", yKey: "count" };
    case "top_users_by_won_revenue_90d":
      return { type: "bar", xKey: "user.fullName", yKey: "wonRevenue" };
    case "new_customers_last_30d":
    case "won_deals_last_30d":
    case "won_deals_last_90d":
      return { type: "table" };
  }
}
